### ISSUE TITLE
[TASK] Get acquainted with MVVM pattern

### ISSUE THREAD

**Issue by RossSihovsk** [RossSihovsk/LifeOS#6]
Read about MVVM architecture pattern and observer pattern. 
Read about Flow in kotlin.
Read about Repository patern
Create simple android  or desktop app with MVVM and Flow in use,

**Comment by VetoForest** [comment]
import androidx.compose.foundation.layout.Column
import androidx.compose.material3.Button
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.mutableStateOf
import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewmodel.compose.viewModel


class MainViewModel : ViewModel() {
    // MutableState to handle our UI state
    var counterState = mutableStateOf(0)

    // Function to increment the counter
    fun incrementCounter() {
        counterState.value++
    }
}

@Composable
fun CounterScreen(mainViewModel: MainViewModel = viewModel()) {
    // UI that reacts to state changes
    Column {
        Text(text = "Counter: ${mainViewModel.counterState.value}")
        Button(onClick = { mainViewModel.incrementCounter() }) {
            Text("Increment")
        }
    }
}

**Comment by VetoForest** [comment]
package com.example.myapplication
import CounterScreen
import androidx.lifecycle.viewmodel.compose.viewModel

import android.os.Bundle
import android.os.CountDownTimer
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.fillMaxHeight
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.size
import androidx.compose.material3.Button
import androidx.compose.material3.ButtonDefaults
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Surface
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.RectangleShape
import androidx.compose.ui.layout.layoutId
import androidx.compose.ui.unit.TextUnit
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.example.myapplication.ui.theme.MyApplicationTheme

class MainActivity : ComponentActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContent {
            MyApplicationTheme {
                // A surface container using the 'background' color from the theme
                Surface(
                    modifier = Modifier.fillMaxSize(),
                    color = MaterialTheme.colorScheme.background
                ) {
                   CounterScreen()
                }
            }
        }
    }}

**Comment by VetoForest** [comment]
package com.example.myapplication
import CounterScreen

import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Surface
import androidx.compose.ui.Modifier
import com.example.myapplication.ui.theme.MyApplicationTheme

class MainActivity : ComponentActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContent {
            MyApplicationTheme {
                // A surface container using the 'background' color from the theme
                Surface(
                    modifier = Modifier.fillMaxSize(),
                    color = MaterialTheme.colorScheme.background
                ) {
                   CounterScreen()
                }
            }
        }
    }}

**Comment by VetoForest** [comment]
https://github.com/RossSihovsk/LifeOS/assets/94835713/7f6d9113-dfaa-404b-b1b3-78170ec8ed40

**Comment by RossSihovsk** [comment]
Well done
