### ISSUE TITLE
[TASK] Get acquainted with Jetpack Compose

### ISSUE THREAD

**Issue by RossSihovsk** [RossSihovsk/LifeOS#7]
This should be done along with #6 
Read about the declarative approach by Jetpack Compose and about an alternative way of creating mobile ui in Android.
Create a simple app with different compose items

**Comment by VetoForest** [comment]
https://github.com/RossSihovsk/LifeOS/assets/94835713/03b57e73-33ef-4b63-a6a5-aca15d5b9c2e
